name: shell commands


on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v3
      - name: echo string
        run: echo " Hello World"
      - name: multi string
        run: |
          node -v
          npm -v
      #- name: python command
      #  run: |
      #    import platform
      #    print(platform.processor())
      #    shell: python
  run-windows-commands:
    runs-on: windows-latest
    needs: ["run-shell-command"] #this depends on the job "run-shell-command" to run first before job "windows-latest"
    #with the "needs" keyword, the two jobs will run in sequence otherwise the two jobs will run in parallel
    steps:
      - name: Directory
        run: Get-Location
      - name: Directory bash
        run: pwd
        shell: bash
    
